name: Demo workflow
on: workflow_dispatch
jobs:
    print: 
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "Hi, Github!"
            - name: Print a few lines
              run: |
                echo first line
                echo second line
                echo third line
