name: Example
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - test
    schedule:
        - cron: '30/9 * * * *'

jobs:
    first:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node: [15, 16, 20]
    second:
        runs-on: ubuntu-latest